# Generated by Django 5.1.7 on 2025-03-14 09:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(blank=True, max_length=150, null=True, verbose_name="Place")),
                ("time", models.TimeField(default="12:00", verbose_name="Time")),
                ("action", models.CharField(max_length=150, verbose_name="Action")),
                ("is_pleasant", models.BooleanField(default=True, verbose_name="Is pleasant")),
                (
                    "periodicity_in_days",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MaxValueValidator(7)],
                        verbose_name="Periodicity in days",
                    ),
                ),
                ("reward", models.CharField(blank=True, max_length=150, null=True, verbose_name="Reward")),
                (
                    "time_to_finish",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(120)],
                        verbose_name="Period",
                    ),
                ),
                ("is_public", models.BooleanField(default=False, verbose_name="Is public")),
                (
                    "connected_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="habits",
                        to="tracker.habit",
                        verbose_name="Connected habit",
                    ),
                ),
            ],
        ),
    ]
