# Generated by Django 5.1.7 on 2025-03-20 09:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity_in_days",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)],
                verbose_name="Periodicity in days",
            ),
        ),
    ]
